service: fileservice
frameworkVersion: "3"

package:
  patterns:
  - 'node_modules/**'

# plugins:
#   - serverless-plugin-include-dependencies  

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  apiGateway:
    shouldStartNameWithService: true
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:GetObject"
            - "s3:PutObject"
            - "s3:ListBucket"
            - "s3:PutBucketAcl"
          Resource: "arn:aws:s3:::${self:custom.bucketName}/*"

  environment:
    bucketName: ${self:custom.bucketName}   

custom:
  bucketName: aws-demo-files

functions:
     
  getobjsignedurl:
    handler: src/services/s3/getFileUrlService.handler
    events:
      - http:
          path: /getobjurl
          method: get
          cors: true  
  
  userRegisterService:
    handler: src/services/s3/userRegisterService.handler
    events:
      - http:
          path: /user/register
          method: post
          cors: true          
  

  filesUploadServices:
    handler: src/services/s3/filesUploadServices.handler
    events:
      - http:
          path: /filesupload
          method: post
          cors: true            
  
  loginService:
    handler: src/services/s3/loginService.handler
    events:
      - http:
          path: /login
          method: post
          cors: true  
  
      
resources:
  Resources:
   MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:  aws-demo-files
      AccessControl: Private
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
              - PUT
              - POST
              - HEAD
            AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
            ExposedHeaders:
              - ETag

#   package:
#    excludeDevDependencies: false

